server:
  servlet:
    context-path: /app
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: JDBC:h2:SD_JPA_db; Mode = PostgreSQL
    username: andrey
    password: admin
  jpa:
    show-sql: false
  h2:
    console:
      enabled: true
